[project]
name = "blockchain-instrument"
authors = ["Your Name <your.email@example.com>"]
description = "A decentralized IoT instrumentation management system on the Stacks blockchain"
telemetry = false
requirements = []
[contracts.instrument-governance]
path = "contracts/instrument-governance.clar"
depends_on = []

[contracts.instrument-verification]
path = "contracts/instrument-verification.clar"
depends_on = []

[contracts.instrument-registry]
path = "contracts/instrument-registry.clar"
depends_on = []

[contracts.instrument-rewards]
path = "contracts/instrument-rewards.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
